### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by Finkregh** [cosmocode/userpagecreate#1]
please add some documentation what values can be entered where

**Comment by micgro42** [comment]
The documentation has been significantly extended, see https://www.dokuwiki.org/plugin:userpagecreate

As stated there: you can use all replacement patterns from https://www.dokuwiki.org/namespace_templates#replacement_patterns, you can use further patterns if your auth-backend provides them (e.g. LDAP) and of course you can use all the syntax from your installed plugins.
